name: despliegueTfg

on:
  push:
    branches:
      - main

jobs:
  despliegue:
    runs-on: [self-hosted, aerogtravel--desktop]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependencias Next.js y construir
        run: |
          cd ordenador/frontend
          npm ci
          cp .env.example .env
          sed -i 's|NEXT_PUBLIC_SITIO_LARAVEL=.*|NEXT_PUBLIC_SITIO_LARAVEL=${{ secrets.NEXT_PUBLIC_SITIO_LARAVEL }}|' .env
          npm run build
          cd ..
          pm2 start ecosystem.config.js --only front-antonio
          pm2 save --force

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Configurar y desplegar Laravel
        run: |
          cd ordenador/backend
          composer install --no-dev --optimize-autoloader
          cp .env.example .env
          sed -i 's|APP_ENV=.*|APP_ENV=production|' .env
          sed -i 's|APP_DEBUG=.*|APP_DEBUG=false|' .env
          sed -i 's|APP_URL=.*|APP_URL=${{ secrets.URL_ANTONIO }}|' .env
          sed -i 's|DB_HOST=.*|DB_HOST=${{ secrets.HOST_ANTONIO }}|' .env
          sed -i 's|DB_PORT=.*|DB_PORT=${{ secrets.PORT_ANTONIO }}|' .env
          sed -i 's|DB_DATABASE=.*|DB_DATABASE=${{ secrets.BASEDATOS_ANTONIO }}|' .env
          sed -i 's|DB_USERNAME=.*|DB_USERNAME=${{ secrets.USUARIO_ANTONIO }}|' .env
          sed -i 's|DB_PASSWORD=.*|DB_PASSWORD=${{ secrets.CONTRASENA_ANTONIO }}|' .env
          APP_KEY=$(php artisan key:generate --show)
          sed -i "s|^APP_KEY=.*|APP_KEY=${APP_KEY}|" .env
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan migrate --force
          cd ..
          pm2 start ecosystem.config.js --only back-antonio
          pm2 save --force

      - name: Arrancar aplicaciones con PM2
        run: |
          cd ordenador
          pm2 start ecosystem.config.js --only nextjs-app
          pm2 start ecosystem.config.js --only laravel-app
          pm2 save --force
