name: despliegueTfg
on:
  push:
    branches:
      - main

jobs:
  despliegue:
    runs-on: [self-hosted, aerogtravel--desktop]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: despliegue nextjs
        run: |
          cd ordenador/frontend
          npm ci
          npm run build
          cd ..
          pm2 start ecosystem.config.js --only front-antonio
          pm2 save --force
